### ISSUE TITLE
GH Actions has no permissions to use rebase command, says Dependabot

### ISSUE THREAD

**Issue by joriswitteman** [bbeesley/gha-auto-dependabot-rebase#515]
I can't get Dependabot to accept rebase commands from the `gh-actions` bot:

> Sorry, only users with push access can use that command.

If I follow up with a personal rebase comment manually, Dependabot accepts.

![image](https://github.com/bbeesley/gha-auto-dependabot-rebase/assets/99750097/b2b43c63-5ebb-4fb3-897d-aba85c78b6c6)

**Comment by bbeesley** [comment]
I believe when it says "push access" it means write permission, so you would need something like

```yaml
    permissions:
      pull-requests: write
      contents: write
```
